var listData = {
  list1: {
    type: "property",
    companies: [
      {name:"上海中海物业管理有限公司", count:7, total:1489, avg:212.7, communities:[{name:"中海瀛台", street:"长桥街道", total:996}, {name:"绿邑翠苑", street:"漕河泾街道", total:152}, {name:"挹翠苑", street:"漕河泾街道", total:116}, {name:"瑞金南苑", street:"斜土路街道", total:109}, {name:"中海馨园", street:"漕河泾街道", total:71}, {name:"幽澜苑", street:"长桥街道", total:30}, {name:"中山苑", street:"枫林路街道", total:15}]},
      {name:"上海汇成物业有限公司", count:17, total:3031, avg:178.3, communities:[{name:"华悦家园", street:"虹梅路街道", total:567}, {name:"华欣家园", street:"华泾镇", total:444}, {name:"华滨家园", street:"长桥街道", total:381}, {name:"长汇景苑", street:"长桥街道", total:298}, {name:"华沁家园", street:"长桥街道", total:253}, {name:"汇成四村", street:"长桥街道", total:204}, {name:"罗秀三村", street:"长桥街道", total:194}, {name:"汇成一村", street:"长桥街道", total:174}, {name:"汇成五村", street:"长桥街道", total:123}, {name:"汇成苑三村", street:"长桥街道", total:121}]},
      {name:"上海阳光投资（集团）物业管理有限公司", count:8, total:1417, avg:177.1, communities:[{name:"尚海湾二期", street:"斜土路街道", total:502}, {name:"尚海湾二期", street:"斜土路街道", total:502}, {name:"阳光绿园", street:"凌云路街道", total:301}, {name:"阳光新景", street:"凌云路街道", total:31}, {name:"阳光名苑", street:"枫林路街道", total:26}, {name:"森陇家园", street:"凌云路街道", total:21}, {name:"长陇苑", street:"凌云路街道", total:20}, {name:"阳光名邸", street:"徐家汇街道", total:14}]},
      {name:"上海金辉物业有限公司", count:7, total:894, avg:127.7, communities:[{name:"梅陇四村", street:"凌云路街道", total:267}, {name:"梅陇五村(多层)", street:"凌云路街道", total:192}, {name:"梅陇六村", street:"凌云路街道", total:157}, {name:"梅陇七村", street:"凌云路街道", total:139}, {name:"梅陇八村", street:"凌云路街道", total:81}, {name:"梅陇五村(高层)", street:"凌云路街道", total:52}, {name:"梅陇路394弄", street:"凌云路街道", total:6}]},
      {name:"上海中星集团申城物业有限公司", count:8, total:994, avg:124.2, communities:[{name:"馨宁公寓", street:"华泾镇", total:477}, {name:"百汇园", street:"龙华街道", total:127}, {name:"馨逸公寓", street:"漕河泾街道", total:94}, {name:"海上名门", street:"漕河泾街道", total:82}, {name:"海上华庭", street:"康健新村街道", total:77}, {name:"寿益坊(南)", street:"康健新村街道", total:63}, {name:"海上名邸", street:"康健新村街道", total:39}, {name:"桂林西街101弄", street:"康健新村街道", total:35}]},
    ]
  },
  list2: [
    {name:"中海瀛台", street:"长桥街道", total:996, buildings:157, floors:5.0, property:"上海中海物业管理有限公司"},
    {name:"日晖六村", street:"斜土路街道", total:711, buildings:122, floors:4.9, property:"上海高建物业有限公司"},
    {name:"华悦家园", street:"虹梅路街道", total:567, buildings:125, floors:7.6, property:"上海汇成物业有限公司"},
    {name:"田林三街坊", street:"田林街道", total:502, buildings:111, floors:5.8, property:"上海徐房物业有限公司"},
    {name:"东湾小区", street:"华泾镇", total:459, buildings:119, floors:5.9, property:"上海润美物业管理有限公司"},
    {name:"华欣家园", street:"华泾镇", total:444, buildings:215, floors:4.3, property:"上海汇成物业有限公司"},
    {name:"宛龙小区", street:"枫林路街道", total:435, buildings:139, floors:4.4, property:"上海高建物业有限公司"},
    {name:"凌云新村", street:"凌云路街道", total:429, buildings:160, floors:6.0, property:"上海徐房物业有限公司"},
    {name:"龙山新村", street:"枫林路街道", total:424, buildings:118, floors:5.2, property:"上海高建物业有限公司"},
    {name:"西木小区", street:"枫林路街道", total:410, buildings:111, floors:5.1, property:"上海高建物业有限公司"},
    {name:"天钥新村", street:"枫林路街道", total:377, buildings:151, floors:5.2, property:"上海高建物业有限公司"},
    {name:"华泾绿苑", street:"华泾镇", total:371, buildings:123, floors:6.0, property:"上海晏鑫实业有限公司"},
    {name:"长桥四村", street:"长桥街道", total:356, buildings:126, floors:6.2, property:"上海安得物业管理有限公司"},
    {name:"安福直管公房", street:"湖南路街道", total:351, buildings:171, floors:2.9, property:"上海衡复物业有限公司"},
    {name:"紫阳花苑", street:"华泾镇", total:338, buildings:136, floors:4.6, property:"上海晏鑫实业有限公司"},
    {name:"梅陇三村", street:"凌云路街道", total:338, buildings:99, floors:5.8, property:"上海徐房物业有限公司"},
    {name:"日晖二村", street:"斜土路街道", total:325, buildings:115, floors:4.6, property:"上海华欣物业管理有限公司"},
    {name:"斜土小区", street:"斜土路街道", total:320, buildings:109, floors:5.8, property:"上海高建物业有限公司"},
    {name:"茶花园", street:"康健新村街道", total:319, buildings:134, floors:6.0, property:"上海安得物业管理有限公司"},
    {name:"梅陇十一村（A块）", street:"凌云路街道", total:310, buildings:63, floors:5.8, property:"上海市工联物业公司"},
    {name:"滨江小区", street:"龙华街道", total:310, buildings:195, floors:5.6, property:"上海凤梧物业管理有限公司"},
    {name:"东安四村", street:"枫林路街道", total:291, buildings:45, floors:5.7, property:"上海高建物业有限公司"},
    {name:"南丹小区", street:"徐家汇街道", total:277, buildings:55, floors:7.0, property:"上海汇虹物业管理有限公司"},
    {name:"石龙路33弄", street:"漕河泾街道", total:277, buildings:78, floors:5.5, property:"上海华东房产物业有限公司"},
    {name:"华东花苑", street:"长桥街道", total:275, buildings:171, floors:5.9, property:"上海轻工物业管理有限公司"},
    {name:"园南一村", street:"长桥街道", total:274, buildings:70, floors:5.7, property:"秀澜（上海）物业管理有限公司"},
    {name:"古美小区", street:"虹梅路街道", total:274, buildings:160, floors:2.9, property:"愿景和家（上海）科技服务有限公司"},
    {name:"零陵小区", street:"徐家汇街道", total:269, buildings:62, floors:5.0, property:"上海高建物业有限公司"},
    {name:"梅陇四村", street:"凌云路街道", total:267, buildings:94, floors:6.9, property:"上海金辉物业有限公司"},
    {name:"楼园", street:"长桥街道", total:267, buildings:150, floors:6.0, property:"上海通翼物业有限公司"},
  ],
  list3: [
    {name:"日晖六村", street:"斜土路街道", total:711, buildings:122, floors:4.9, property:"上海高建物业有限公司"},
    {name:"西木小区", street:"枫林路街道", total:410, buildings:111, floors:5.1, property:"上海高建物业有限公司"},
    {name:"梅陇三村", street:"凌云路街道", total:338, buildings:99, floors:5.8, property:"上海徐房物业有限公司"},
    {name:"零陵小区", street:"徐家汇街道", total:269, buildings:62, floors:5.0, property:"上海高建物业有限公司"},
    {name:"梅陇四村", street:"凌云路街道", total:267, buildings:94, floors:6.9, property:"上海金辉物业有限公司"},
    {name:"谨斜小区", street:"枫林路街道", total:227, buildings:63, floors:5.0, property:"上海高建物业有限公司"},
    {name:"江南新村", street:"斜土路街道", total:225, buildings:114, floors:4.5, property:"上海高建物业有限公司"},
    {name:"田林十一村多层", street:"田林街道", total:158, buildings:52, floors:5.9, property:"上海徐房物业有限公司"},
    {name:"永太小区", street:"天平路街道", total:139, buildings:36, floors:5.4, property:"上海衡复物业有限公司"},
    {name:"田林二街坊", street:"田林街道", total:133, buildings:47, floors:6.0, property:"上海徐房物业有限公司"},
    {name:"月季园", street:"康健新村街道", total:133, buildings:154, floors:5.4, property:"上海轻工物业管理有限公司"},
    {name:"宛南五村", street:"枫林路街道", total:130, buildings:29, floors:5.2, property:"上海高建物业有限公司"},
    {name:"虹二小区", street:"徐家汇街道", total:124, buildings:36, floors:4.6, property:"上海高建物业有限公司"},
    {name:"大三大四", street:"斜土路街道", total:124, buildings:45, floors:4.4, property:"上海高建物业有限公司"},
    {name:"东安五村", street:"枫林路街道", total:117, buildings:42, floors:4.6, property:"上海高建物业有限公司"},
    {name:"紫竹园", street:"康健新村街道", total:108, buildings:50, floors:6.0, property:"上海轻工物业管理有限公司"},
    {name:"汇贤雅居", street:"徐家汇街道", total:99, buildings:58, floors:4.6, property:"上海虹叶物业管理有限公司"},
    {name:"龙南内三村", street:"龙华街道", total:97, buildings:25, floors:7.0, property:"上海亿绵物业管理有限公司"},
    {name:"岳阳小区", street:"天平路街道", total:94, buildings:17, floors:5.9, property:"上海衡复物业有限公司"},
    {name:"宜德苑", street:"田林街道", total:89, buildings:42, floors:5.5, property:"上海华欣物业管理有限公司"},
  ],
  list4: [
    {name:"尚海湾二期", street:"斜土路街道", total:502, buildings:21, floors:16.5, property:"上海阳光投资（集团）物业管理有限公司"},
    {name:"尚海湾二期", street:"斜土路街道", total:502, buildings:0, floors:0, property:"上海阳光投资（集团）物业管理有限公司"},
    {name:"馨宁公寓", street:"华泾镇", total:477, buildings:86, floors:8.3, property:"上海中星集团申城物业有限公司"},
    {name:"安福直管公房", street:"湖南路街道", total:351, buildings:171, floors:2.9, property:"上海衡复物业有限公司"},
    {name:"鑫桂苑·侨高中心", street:"虹梅路街道", total:315, buildings:1, floors:0.0, property:"上海万科物业服务有限公司"},
    {name:"长汇景苑", street:"长桥街道", total:298, buildings:1, floors:0.0, property:"上海汇成物业有限公司"},
    {name:"太原直管公房", street:"天平路街道", total:244, buildings:178, floors:2.9, property:"上海衡复物业有限公司"},
    {name:"陕新直管公房", street:"湖南路街道", total:240, buildings:217, floors:2.8, property:"上海衡复物业有限公司"},
    {name:"陕西直管公房", street:"天平路街道", total:225, buildings:170, floors:3.0, property:"上海衡复物业有限公司"},
    {name:"建新直管公房", street:"天平路街道", total:213, buildings:301, floors:2.8, property:"上海衡复物业有限公司"},
    {name:"永太直管公房", street:"天平路街道", total:212, buildings:297, floors:2.8, property:"上海衡复物业有限公司"},
    {name:"欣嘉苑1-3期", street:"虹梅路街道", total:205, buildings:82, floors:5.0, property:"上海锦龙物业管理有限公司"},
    {name:"淮中直管公房", street:"湖南路街道", total:201, buildings:131, floors:2.7, property:"上海衡复物业有限公司"},
    {name:"余庆直管公房", street:"天平路街道", total:194, buildings:79, floors:2.9, property:"上海衡复物业有限公司"},
    {name:"桃源村直管公房", street:"天平路街道", total:192, buildings:233, floors:2.8, property:"上海衡复物业有限公司"},
    {name:"悦汇长庭", street:"长桥街道", total:190, buildings:0, floors:0, property:"-"},
    {name:"安亭直管公房", street:"天平路街道", total:187, buildings:111, floors:2.7, property:"上海衡复物业有限公司"},
    {name:"新湖云庭", street:"枫林路街道", total:178, buildings:5, floors:18.8, property:"上海益镇物业管理有限公司"},
    {name:"息村直管公房", street:"天平路街道", total:171, buildings:176, floors:2.7, property:"上海衡复物业有限公司"},
    {name:"复永直管公房", street:"湖南路街道", total:161, buildings:63, floors:2.7, property:"上海衡复物业有限公司"},
    {name:"尚海湾一期", street:"斜土路街道", total:154, buildings:0, floors:0, property:"-"},
    {name:"延庆直管公房", street:"湖南路街道", total:152, buildings:186, floors:3.0, property:"上海衡复物业有限公司"},
    {name:"上海新村直管公房", street:"天平路街道", total:144, buildings:86, floors:2.8, property:"上海衡复物业有限公司"},
    {name:"永嘉新村直管公房", street:"天平路街道", total:140, buildings:87, floors:2.7, property:"上海衡复物业有限公司"},
    {name:"宝能华庭", street:"龙华街道", total:136, buildings:1, floors:0.0, property:"-"},
    {name:"金波直管公房", street:"湖南路街道", total:128, buildings:85, floors:2.6, property:"上海衡复物业有限公司"},
    {name:"百汇园", street:"龙华街道", total:127, buildings:66, floors:12.7, property:"上海中星集团申城物业有限公司"},
    {name:"新乐直管公房", street:"湖南路街道", total:126, buildings:140, floors:2.9, property:"上海衡复物业有限公司"},
    {name:"慎成直管公房", street:"天平路街道", total:124, buildings:243, floors:2.4, property:"上海衡复物业有限公司"},
    {name:"永康直管公房", street:"天平路街道", total:121, buildings:257, floors:2.4, property:"上海衡复物业有限公司"},
  ],
  list5: [
    {name:"中海瀛台", street:"长桥街道", total:996, buildings:157, floors:5.0, property:"上海中海物业管理有限公司", ywhPct:80.5},
    {name:"日晖六村", street:"斜土路街道", total:711, buildings:122, floors:4.9, property:"上海高建物业有限公司", ywhPct:1.4},
    {name:"华悦家园", street:"虹梅路街道", total:567, buildings:125, floors:7.6, property:"上海汇成物业有限公司", ywhPct:3.5},
    {name:"田林三街坊", street:"田林街道", total:502, buildings:111, floors:5.8, property:"上海徐房物业有限公司", ywhPct:1.6},
    {name:"东湾小区", street:"华泾镇", total:459, buildings:119, floors:5.9, property:"上海润美物业管理有限公司", ywhPct:3.3},
    {name:"华欣家园", street:"华泾镇", total:444, buildings:215, floors:4.3, property:"上海汇成物业有限公司", ywhPct:1.8},
    {name:"宛龙小区", street:"枫林路街道", total:435, buildings:139, floors:4.4, property:"上海高建物业有限公司", ywhPct:0.9},
    {name:"凌云新村", street:"凌云路街道", total:429, buildings:160, floors:6.0, property:"上海徐房物业有限公司", ywhPct:4.7},
    {name:"龙山新村", street:"枫林路街道", total:424, buildings:118, floors:5.2, property:"上海高建物业有限公司", ywhPct:1.7},
    {name:"西木小区", street:"枫林路街道", total:410, buildings:111, floors:5.1, property:"上海高建物业有限公司", ywhPct:4.1},
    {name:"华滨家园", street:"长桥街道", total:381, buildings:81, floors:8.2, property:"上海汇成物业有限公司", ywhPct:10.8},
    {name:"天钥新村", street:"枫林路街道", total:377, buildings:151, floors:5.2, property:"上海高建物业有限公司", ywhPct:1.1},
    {name:"华泾绿苑", street:"华泾镇", total:371, buildings:123, floors:6.0, property:"上海晏鑫实业有限公司", ywhPct:4.6},
    {name:"盛华景苑", street:"华泾镇", total:356, buildings:62, floors:8.5, property:"上海永升物业管理有限公司", ywhPct:4.8},
    {name:"长桥四村", street:"长桥街道", total:356, buildings:126, floors:6.2, property:"上海安得物业管理有限公司", ywhPct:7.0},
    {name:"紫阳花苑", street:"华泾镇", total:338, buildings:136, floors:4.6, property:"上海晏鑫实业有限公司", ywhPct:2.1},
    {name:"梅陇三村", street:"凌云路街道", total:338, buildings:99, floors:5.8, property:"上海徐房物业有限公司", ywhPct:10.4},
    {name:"日晖二村", street:"斜土路街道", total:325, buildings:115, floors:4.6, property:"上海华欣物业管理有限公司", ywhPct:4.0},
    {name:"斜土小区", street:"斜土路街道", total:320, buildings:109, floors:5.8, property:"上海高建物业有限公司", ywhPct:0.9},
    {name:"茶花园", street:"康健新村街道", total:319, buildings:134, floors:6.0, property:"上海安得物业管理有限公司", ywhPct:14.4},
  ],
  list6: [
    {name:"中海瀛台", street:"长桥街道", total:996, buildings:157, floors:5.0, property:"上海中海物业管理有限公司"},
    {name:"日晖六村", street:"斜土路街道", total:711, buildings:122, floors:4.9, property:"上海高建物业有限公司"},
    {name:"华悦家园", street:"虹梅路街道", total:567, buildings:125, floors:7.6, property:"上海汇成物业有限公司"},
    {name:"田林三街坊", street:"田林街道", total:502, buildings:111, floors:5.8, property:"上海徐房物业有限公司"},
    {name:"馨宁公寓", street:"华泾镇", total:477, buildings:86, floors:8.3, property:"上海中星集团申城物业有限公司"},
    {name:"东湾小区", street:"华泾镇", total:459, buildings:119, floors:5.9, property:"上海润美物业管理有限公司"},
    {name:"华欣家园", street:"华泾镇", total:444, buildings:215, floors:4.3, property:"上海汇成物业有限公司"},
    {name:"宛龙小区", street:"枫林路街道", total:435, buildings:139, floors:4.4, property:"上海高建物业有限公司"},
    {name:"凌云新村", street:"凌云路街道", total:429, buildings:160, floors:6.0, property:"上海徐房物业有限公司"},
    {name:"龙山新村", street:"枫林路街道", total:424, buildings:118, floors:5.2, property:"上海高建物业有限公司"},
    {name:"西木小区", street:"枫林路街道", total:410, buildings:111, floors:5.1, property:"上海高建物业有限公司"},
    {name:"华滨家园", street:"长桥街道", total:381, buildings:81, floors:8.2, property:"上海汇成物业有限公司"},
    {name:"天钥新村", street:"枫林路街道", total:377, buildings:151, floors:5.2, property:"上海高建物业有限公司"},
    {name:"华泾绿苑", street:"华泾镇", total:371, buildings:123, floors:6.0, property:"上海晏鑫实业有限公司"},
    {name:"长桥四村", street:"长桥街道", total:356, buildings:126, floors:6.2, property:"上海安得物业管理有限公司"},
    {name:"盛华景苑", street:"华泾镇", total:356, buildings:62, floors:8.5, property:"上海永升物业管理有限公司"},
    {name:"安福直管公房", street:"湖南路街道", total:351, buildings:171, floors:2.9, property:"上海衡复物业有限公司"},
    {name:"紫阳花苑", street:"华泾镇", total:338, buildings:136, floors:4.6, property:"上海晏鑫实业有限公司"},
    {name:"梅陇三村", street:"凌云路街道", total:338, buildings:99, floors:5.8, property:"上海徐房物业有限公司"},
    {name:"日晖二村", street:"斜土路街道", total:325, buildings:115, floors:4.6, property:"上海华欣物业管理有限公司"},
  ],
  list7: [
    {name:"徐汇苑", street:"枫林路街道", total:92, buildings:22, floors:13.8, property:"上海航新物业管理有限公司", yoy:145.5},
    {name:"实业公寓", street:"徐家汇街道", total:111, buildings:2, floors:0.0, property:"上海百联物业管理有限公司", yoy:131.8},
    {name:"徐家汇花园", street:"枫林路街道", total:112, buildings:78, floors:5.5, property:"上海汇银物业管理有限公司", yoy:125.9},
    {name:"金牛苑", street:"漕河泾街道", total:83, buildings:211, floors:1.7, property:"上海梓班物业管理有限公司", yoy:120.8},
    {name:"东方巴黎霞飞苑", street:"湖南路街道", total:100, buildings:6, floors:13.2, property:"上海东湖物业管理有限公司", yoy:119.2},
    {name:"嘉汇广场", street:"徐家汇街道", total:124, buildings:4, floors:23.0, property:"上海龙湖物业服务有限公司", yoy:116.7},
    {name:"钦州公寓", street:"田林街道", total:120, buildings:3, floors:18.0, property:"上海安得物业管理有限公司", yoy:113.0},
    {name:"虹桥大仕馆", street:"田林街道", total:141, buildings:15, floors:10.5, property:"上海锦江物业管理有限公司", yoy:109.7},
    {name:"尚海湾一期", street:"斜土路街道", total:154, buildings:0, floors:0, property:"-", yoy:102.6},
    {name:"尚海湾一期", street:"斜土路街道", total:154, buildings:40, floors:13.0, property:"上海金地物业服务有限公司", yoy:102.6},
    {name:"裕德路66弄", street:"徐家汇街道", total:75, buildings:11, floors:5.9, property:"上海佰事德物业管理有限公司", yoy:100.0},
    {name:"绿邑翠苑", street:"漕河泾街道", total:152, buildings:15, floors:9.4, property:"上海中海物业管理有限公司", yoy:93.6},
    {name:"宛南六村", street:"枫林路街道", total:125, buildings:45, floors:5.2, property:"上海高建物业有限公司", yoy:86.5},
    {name:"紫元大厦", street:"徐家汇街道", total:108, buildings:1, floors:20.0, property:"上海外经贸物业管理有限公司", yoy:85.3},
    {name:"衡园", street:"斜土路街道", total:68, buildings:36, floors:13.1, property:"上海良宇物业管理有限公司", yoy:85.0},
    {name:"俞三小区", street:"龙华街道", total:84, buildings:39, floors:6.0, property:"上海华晅投资管理有限公司", yoy:81.8},
    {name:"长海坊", street:"康健新村街道", total:72, buildings:24, floors:5.9, property:"沃棠（上海）物业管理有限公司", yoy:78.3},
    {name:"徐汇世家花园", street:"田林街道", total:115, buildings:0, floors:0, property:"-", yoy:69.7},
    {name:"徐汇世家花园", street:"田林街道", total:115, buildings:35, floors:30.8, property:"上海丰柏物业管理有限公司", yoy:69.7},
    {name:"东湾小区", street:"华泾镇", total:459, buildings:119, floors:5.9, property:"上海润美物业管理有限公司", yoy:67.3},
  ],
};